echokit_diy:
  name: EchoKey DIY
  description: "EchoKit is a fun voice AI agent that can chat with your out of the box. But more importantly, it is also a complete toolkit that enables YOU (and your kids / students) to build cutting edge AI agent systems. NOTE: We will manually assemble, flash, and test each device toolkit before shipping. Expect delivery in up to 3 weeks for international orders. Thank you for your patience."
  staging:
    price: 0.1
    shipping: 0
  production:
    price: 49.00
    shipping: 4.99

demo:
  name: Demo Title
  description: "Demo description."
  staging:
    price: 0.1
    shipping: 0
  production:
    price: 0.01
    shipping: 0
